### ISSUE TITLE
Invalid address error when using injected provider

### ISSUE THREAD

**Issue by flyswatter** [ethereum/browser-solidity#342]
Over at MetaMask, we had [an issue submitted](https://github.com/MetaMask/metamask-plugin/issues/880) by @drcode regarding MetaMask/browser-solidity compatibility, and I could use your help to track down.

The error thrown is `Uncaught Error: invalid address(…)`, thrown from browser-solidity when the payload has an `undefined` `from` field.

For some reason it seems that browser-solidity is no longer successfully building its transaction parameters using the currently injected selected address at `web3.eth.accounts[0]` or `web3.eth.coinbase`.

In the `Method.prototype.buildCall` function, you can see this line:
```
var payload = method.toPayload(Array.prototype.slice.call(arguments));
```

The input arguments are very minimal, and the resulting `payload` value lacks a defined sender:
```javascript
{from: undefined, to: undefined, data: "0x606060405234610000575b33600060006101000a8154817000816000905550600101610594565b5090565b50505b5056", value: "0x0", gas: 449552}
```

This makes it look like the `method.toPayload()` method is failing to pull out the current address from the injected `web3`.

Unfortunately, when I did [a search of this repository](https://github.com/ethereum/browser-solidity/search?utf8=%E2%9C%93&q=toPayload), I saw no `toPayload` reference anywhere, so now I'm confused.

This *seems to be* a browser-solidity bug to me right now, but without the original source code to search & reference, it will be hard for me to track down.  Any clues?

**Comment by kumavis** [comment]
@flyswatter  I think `var payload = method.toPayload(Array.prototype.slice.call(arguments));` is in web3 and thats why you're not seeing it in this repo

an aside:
web3 has previously not allowed you to submit a tx without a specified sender. I don't know if they still enforce this but in my opinion **they shouldn't**, it can be autofilled by the user-agent (mist/metamask).

**Comment by flyswatter** [comment]
I agree it would seem reasonable & kinda cool to not require a specified sender.  Less code for dapp developers.  Let the provider throw an error if it can't fill a sender in.

**Comment by flyswatter** [comment]
Since that looks like it's `web3`, I'll continue exploring the stack fro where browser-solidity should be grabbing the `from` value...

**Comment by flyswatter** [comment]
The stack is simply too deep. I cannot find where browser-solidity is assembling the params. I could really use the help of a `browser-solidity` dev tracking this down.

**Comment by axic** [comment]
I think it was broken by #335.

**Comment by drcode** [comment]
This error also happens without metamask, just using geth and the "Web3 Provider" mode of solidity.

**Comment by Chillli** [comment]
This error also happens in Mist.

**Comment by flyswatter** [comment]
If axic is right, and #335 broke this, to check out a working version, you should git pull and checkout the version `b4a512ddba1c71073afb12d44cf5c8b833baa0e2`.

**Comment by flyswatter** [comment]
So, the production `browser-solidity` has been broken for a week now.

Who is the maintainer whose attention we need to get here?

**Comment by MichaelMaurer** [comment]
I confirm that using version `b4a512ddba1c71073afb12d44cf5c8b833baa0e2` works with MetaMask v2.13.11. Here is what I did:
```
git clone git@github.com:ethereum/browser-solidity.git
cd browser-solidity
git checkout b4a512ddba1c71073afb12d44cf5c8b833baa0e2
npm install
npm run build
npm run serve    # starts webserver on port 8080
```
Then I pointed Chrome to http://localhost:8080 to bring up my local browser-solidity, clicked the cube icon, and selected "Injected Web3" to use MetaMask.

**Comment by kumavis** [comment]
@yann300 @chriseth ^ the PR  #335 broke this

**Comment by yann300** [comment]
This PR should fix it
https://github.com/ethereum/browser-solidity/pull/341
but it is not yet merged. @axic could we push that?

**Comment by megachucky** [comment]
So do I understand correctly that this issue is fixed now? 

I still have the same issue when I use the Solidity Browser web UI...

**Comment by yann300** [comment]
The issue is fixed on my side with this basic contract
`
contract intLocal {
    address public _l;
    function intLocal () {
    _l = msg.sender;
    }
 }
`

Could you post the code of the contract here please, i will try to reproduce.

**Comment by yann300** [comment]
@megachucky perhaps try clearing the browser cache

**Comment by megachucky** [comment]
I cleared the Chrome cache, deleted all cookies and tried @yann300 's contract example with the most recent compiler (0.4.7-nightly.2016.12.13+commit.9d607345.Emscripten.clang).

Still the same issue. 

Does it  work for you with the "online version" at https://ethereum.github.io/browser-solidity, or are you using another Solidity Browser?

**Comment by yann300** [comment]
yes... you are using metamask right? on ropsten?

**Comment by megachucky** [comment]
I am not even getting to that step with Metamask because I still get the exception of "address not supported for state ..." in the formal verification of Solidity Browser. You do not get this error anymore? Which compiler version do you use? 

I might check this on another computer later today to doublecheck that it is not any kind of cache / cookie error in my Chrome browser...

**Comment by chriseth** [comment]
The error `"address not supported for state ..."` is unrelated to this issue. Not all valid code is supported by the formal verification module.

**Comment by flyswatter** [comment]
It sounds to me like this bug has been fixed, thank you!!!

**Comment by megachucky** [comment]
Finally, I could also try it out again. I also can confirm that it works again. I can successfully create contracts with Solidity Browser. Due to the "verfification error", Metamask complains that the contract has an exception, but it still executes the transaction successfully.

**Comment by flyswatter** [comment]
Can you help clarify what verification error is showing an incorrect warning on MetaMask?  Is there a better way we could handle it?

**Comment by axic** [comment]
@megachucky it is not a "verification error". The Solidity compiler can output multiple artefacts, one of them is a Why3 Formal Verification source code. This is visible in the "formal verification" tab. That however doesn't support every feature of the language.

The warning provided by it can be ignored unless you need formal verification.

I am not sure how this is related to Metamask.

**Comment by flyswatter** [comment]
Ahh, well MetaMask uses the error-first syntax to identify errors, and uses that first argument's message in the UI. Sounds like the error argument of the callback is used for metadata, @axic?

**Comment by axic** [comment]
Which callback are we talking about? This is the compilation process, that shouldn't have anything to do with Metamask.

**Comment by flyswatter** [comment]
I'm actually not 100% sure, but I believe they're talking about [this publication error](https://github.com/MetaMask/metamask-plugin/issues/924).

**Comment by axic** [comment]
Just compile this code in browser-solidity and switch to the tab with the "tick" as an icon, that'll show why3 compilation errors (but that doesn't stop the rest from functioning):
```
contract A {
  address public a;
}
```

**Comment by flyswatter** [comment]
Ok, I've reproduced & logged the state, I'll be able to easily debug this tomorrow.

**Comment by megachucky** [comment]
@flyswatter Yes, you are right (sorry for not being more clear). I meant exactly this error in MetaMask you linked to. 

To summarize: 
In Solidity Browser, the verification tab always shows an error regarding address not supported, like: 
"Untitled:3:5: Error: Type "address" not supported for state variable. address public owner;"

Anyway, everything works as expected, I can compile and create the contract and run transactions. 

When MetaMask pops up to confirm the transaction, I get this notifcation:
"Transaction Error. Exception thrown in contract code." - However, again, everything works fine.

**Comment by flyswatter** [comment]
This bug happens because we have [this line](https://github.com/MetaMask/metamask-plugin/blob/dev/app/scripts/lib/tx-utils.js#L43) in our tx response parser.

It says:
```javascript
    // all gas used - must be an error
    if (estimatedGasHex === txData.txParams.gas) {
      txData.simulationFails = true
    }
```
It seems the assumption "all gas used is an error" is incorrect when using the compiler, for which browser-solidity seems to perfectly predict the correct gas usage for.

We could either entirely remove this block, and leave OOG error detection to the TxManager, or try to improve the conditions of the assumption.  I'm leaning towards the former for simplicity & nice abstraction.

**Comment by kumavis** [comment]
@flyswatter yeah I agree, this should be handled externally, we dont have enough information here

**Comment by sagargohil** [comment]
Hi All, i am facing this issue.. so this is not yet resolved. 
I am using browser solidity and meta mask, previously everything working properly. please let me know if someone has solution of it.
![image](https://cloud.githubusercontent.com/assets/24582440/22930098/b766154e-f2e4-11e6-96c7-abe6aec7a341.png)

**Comment by yann300** [comment]
that stuff is another issue.
this is more related to https://github.com/ethereum/go-ethereum/issues/3653

**Comment by kumavis** [comment]
@sagargohil i cant tell from your screenshot what the issue is
