### ISSUE TITLE
File upload is broken

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#80]
File upload in firefox is broken. File selection works fine and also upload (file is visible after reload), but the error `editor is undefined` appears here:
```
 this.onChangeSetup = function (onChange) {
    editor.getSession().on('change', onChange);
    editor.on('changeSession', function () {
      editor.getSession().on('change', onChange);
      /// ^ error here
      onChange();
    });
  };
```

**Comment by Denton-L** [comment]
I'll take a look at it.

**Comment by Denton-L** [comment]
This is related to #53 and #71.

**Comment by redsquirrel** [comment]
#53 and #71 should be fixed once #73 is merged.

**Comment by Denton-L** [comment]
Unfortunately, even though #73 got merged, it appears that file uploading is still broken.
